{
 "title": "Solar Panel MPEI DEMO",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total AC Power, W",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "W" }
   ],
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    x as \"Total AC Power\"\nFROM $table\n\nWHERE $timeFilter and parameter_name =='Total AC Power[W]' and id==1\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(\"t\"), 30) * 30) * 1000 as t,\n    x as \"Total AC Power\"\nFROM solar.telemetry\n\nWHERE \"t\" >= toDateTime(1605001063) and parameter_name =='Total AC Power[W]' and id==1\n\nORDER BY t",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "t, °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    x as \"temp\"\nFROM $table\n\nWHERE $timeFilter and parameter_name == 'Temperature' and id==1\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(\"t\"), 30) * 30) * 1000 as t,\n    x as \"temp\"\nFROM solar.telemetry\n\nWHERE \"t\" >= toDateTime(1605000986) and parameter_name == 'Temperature' and id==1\n\nORDER BY t",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "Panel Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "V" }
   ],
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    x as \"PV1 Voltage\"\nFROM $table\n\nWHERE $timeFilter\nand parameter_name=='PV1 Voltage[V]' and id==1\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(\"t\"), 30) * 30) * 1000 as t,\n    x as \"PV1 Voltage\"\nFROM solar.telemetry\n\nWHERE \"t\" >= toDateTime(1605001010)\nand parameter_name=='PV1 Voltage[V]' and id==1\nORDER BY t",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "f, Hz",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "f, Hz" }
   ],
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    x as frequency\nFROM $table\n\nWHERE $timeFilter and parameter_name=='Grid frequency(R Phase)[Hz]' and id==1\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(\"t\"), 30) * 30) * 1000 as t,\n    x as frequency\nFROM solar.telemetry\n\nWHERE \"t\" >= toDateTime(1605000916) and parameter_name=='Grid frequency(R Phase)[Hz]' and id==1\n\nORDER BY t",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "Voltage pulsation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    (max(x)-min(x))/(2*avg(x))*100  as \"Voltage pulsation\"\nFROM $table\n\nWHERE toDate(t)==toDate(now())\nand parameter_name=='PV1 Voltage[V]' and x>0 and id==1",
     "rawQuery": "SELECT\n    (max(x)-min(x))/(2*avg(x))*100  as \"Voltage pulsation\"\nFROM solar.telemetry\n\nWHERE toDate(t)==toDate(now())\nand parameter_name=='PV1 Voltage[V]' and x>0 and id==1",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(t) as d,\n    sum(x)/12/1000 as \"Generated energy\"\nFROM $table\nWHERE toDate(t)=toDate(now()) and x>0 and parameter_name like '%PV1 Input Power%' and id==1\ngroup by d\nORDER BY d",
     "rawQuery": "SELECT\n    toDate(t) as d,\n    sum(x)/12/1000 as \"Generated energy\"\nFROM solar.telemetry\nWHERE toDate(t)=toDate(now()) and x>0 and parameter_name like '%PV1 Input Power%' and id==1\ngroup by d\nORDER BY d",
     "round": "0s",
     "table": "telemetry"
    },
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t,\n    x as \"Energy generation forecast for today\"\nFROM $table\n\nWHERE\n     x > 0\n    and parameter_name == 'Generation_prediction'\n    and id == 1\nORDER BY t desc\n\nLIMIT 1\n",
     "rawQuery": "SELECT\n    t,\n    x as \"Energy generation forecast for today\"\nFROM solar.telemetry\n\nWHERE\n     x > 0\n    and parameter_name == 'Generation_prediction'\n    and id == 1\nORDER BY t desc\n\nLIMIT 1",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  },
  {
   "title": "average ΔmHZ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ΔmHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "solar",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(t) as d,\n    round(median(abs(x-50))*1000) as delta_frequency\nFROM $table\nWHERE toDate(t)=toDate(now())  and x>0 and parameter_name=='Grid frequency(R Phase)[Hz]' and id==1\ngroup by d\nORDER BY d desc limit 1\n",
     "rawQuery": "SELECT\n    toDate(t) as d,\n    round(median(abs(x-50))*1000) as delta_frequency\nFROM solar.telemetry\nWHERE toDate(t)=toDate(now())  and x>0 and parameter_name=='Grid frequency(R Phase)[Hz]' and id==1\ngroup by d\nORDER BY d desc limit 1",
     "round": "0s",
     "table": "telemetry"
    }
   ]
  }
 ]
}